lumirlumir/lumirlumir-configs:
  - source: ./.github/sync-client.yml
    dest: ./clients/npm-bananass.yml
  # ./.github/workflows
  - source: ./.github/workflows/lint.yml
    dest: ./configs/.github/workflows/lint.yml
  - source: ./.github/workflows/publish.yml
    dest: ./configs/.github/workflows/publish.yml
  - source: ./.github/workflows/pull-request.yml
    dest: ./configs/.github/workflows/pull-request.yml
  - source: ./.github/workflows/release.yml
    dest: ./configs/.github/workflows/release.yml
  - source: ./.github/workflows/sync-client.yml
    dest: ./configs/.github/workflows/sync-client.yml
  - source: ./.github/workflows/test.yml
    dest: ./configs/.github/workflows/test.yml
  - source: ./.github/workflows/version-monorepo.yml
    dest: ./configs/.github/workflows/version-monorepo.yml
  # ./.github
  - source: ./.github/CODEOWNERS
    dest: ./configs/.github/CODEOWNERS
  - source: ./.github/dependabot.yml
    dest: ./configs/.github/dependabot.yml
  - source: ./.github/release.yml
    dest: ./configs/.github/release.yml
  # ./.husky
  - source: ./.husky/pre-commit
    dest: ./configs/.husky/pre-commit
  # ./.vscode
  - source: ./.vscode/extensions.json
    dest: ./configs/.vscode/npm-extensions.json
  - source: ./.vscode/settings.json
    dest: ./configs/.vscode/settings.json
  # ./scripts
  - source: ./scripts/cp.mjs
    dest: ./configs/scripts/cp.mjs
  - source: ./scripts/vercel-ignore-command.sh
    dest: ./configs/scripts/vercel-ignore-command.sh
  # ./
  - source: ./.editorconfig
    dest: ./configs/.editorconfig
  - source: ./.gitattributes
    dest: ./configs/.gitattributes
  - source: ./.gitignore
    dest: ./configs/.gitignore
  - source: ./.markdownlint.json
    dest: ./configs/.markdownlint.json
  - source: ./.markdownlintignore
    dest: ./configs/.markdownlintignore
  - source: ./.nvmrc
    dest: ./configs/.nvmrc
  - source: ./.prettierignore
    dest: ./configs/.prettierignore
  - source: ./.textlintrc.cjs
    dest: ./configs/.textlintrc.cjs
  - source: ./LICENSE.md
    dest: ./configs/LICENSE.md
  - source: ./VScode.code-workspace
    dest: ./configs/VScode.code-workspace
  - source: ./lint-staged.config.mjs
    dest: ./configs/lint-staged.config.mjs
  - source: ./prettier.config.mjs
    dest: ./configs/prettier.config.mjs
  # tsconfig.json
  - source: ./packages/bananass/tsconfig.json
    dest: ./configs/tsconfig.json
  - source: ./packages/bananass-utils-console/tsconfig.json
    dest: ./configs/tsconfig.json
  - source: ./packages/create-bananass/tsconfig.json
    dest: ./configs/tsconfig.json
  - source: ./packages/eslint-config-bananass/tsconfig.json
    dest: ./configs/tsconfig.json
  - source: ./packages/prettier-config-bananass/tsconfig.json
    dest: ./configs/tsconfig.json
