/**
 * @fileoverview Docusaurus sidebars configuration.
 *
 * This runs in Node.js - Don't use client-side code here. (Browser APIs, JSX...)
 */

// --------------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------------

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  learnSidebar: [{ type: 'autogenerated', dirName: 'learn' }],
  apisSidebar: [{ type: 'autogenerated', dirName: 'apis' }],
  solutionsSidebar: [{ type: 'autogenerated', dirName: 'solutions' }],
};
